import { Fragment, useEffect, useState } from 'react';
import { collection, doc, getDoc, getDocs, query, where } from 'firebase/firestore';
import { RegionLogos } from '../../components/RegionLogos';
import { KPSeasonOverview } from '../kp/KPSeasonOverview';
import { db } from '../../services/dnsCore';
import type { DNSAccessContext, DNSPermission } from '../../types/access';
import type { ModuleId } from '../../config/modules';

type Fact = Record<string, unknown>;
type RecordData = { id: string; domain: string; label: string; sheet: string; organizationId: string; reportingAreaId: string; facts: Fact[]; recordType?: string; provenance?: Record<string, unknown> };
type Control = { reportingAreaId: string; reportedQuantity: number; reportedAmount: number; detailQuantity: number; detailAmount: number; quantityDifference: number; amountDifference: number };
type Summary = { reportedQuantity?: number; reportedAmount?: number; controls?: Control[] };
const AREA_NAMES: Record<string, [string,string]> = {
 antholzertal:['Valle di Anterselva','Antholzertal'], 'gsiesertal-welsberg-taisten':['Val Casies–Monguelfo–Tesido','Gsiesertal–Welsberg–Taisten'],
 'drei-zinnen':['3 Cime Dolomites','3 Zinnen Dolomites'],osttirol:['Osttirol','Osttirol'],ahrntal:['Valle Aurina','Ahrntal'],
 'seiser-alm-dolomites-val-gardena':['Alpe di Siusi–Val Gardena','Seiser Alm–Gröden'],'cortina-d-ampezzo':['Cortina d’Ampezzo','Cortina d’Ampezzo'],'val-comelico':['Comelico','Comelico'],
};
const PRODUCT_NAMES: Record<string,[string,string]>={day:['Giornaliero','Tageskarte'],'wk-area':['Settimanale area','Wochenkarte Area'],'wk-dns':['Settimanale DNS','Wochenkarte DNS'],'sk-area':['Stagionale area','Saisonkarte Area'],'sk-dns':['Stagionale DNS','Saisonkarte DNS'],'sk-instructor':['Maestri fondo','Langlauflehrer']};

export function HistoricalSeason({ seasonId, module, access, language }: { seasonId: string; module: ModuleId; access: DNSAccessContext | null; language: 'it' | 'de' }) {
 const [records,setRecords]=useState<RecordData[]>([]);const [summary,setSummary]=useState<Summary|null>(null);const [status,setStatus]=useState('');const it=language==='it';
 const domains=seasonId==='2024-25'
  ? (module==='season'||module==='verification'?['sales','snow','costs']:module==='sales'?['sales']:module==='kp'?['snow','costs']:[])
  : (module==='season'||module==='verification')?['sales','orders','pricing','kp']:module==='sales'?['sales']:module==='orders'?['orders']:module==='kp'?['kp']:module==='pricing'?['pricing']:[];
 useEffect(()=>{let current=true;setRecords([]);setSummary(null);setStatus(it?'Caricamento storico…':'Historie wird geladen…');
  async function load(){if(!access?.profile?.active)throw new Error(it?'Accedi per consultare lo storico.':'Zum Lesen der Historie anmelden.');
   const loaded=await Promise.all(domains.map(async domain=>{const permission:DNSPermission=domain==='sales'?'ticketSales.read':domain==='orders'?'ticketOrders.read':domain==='kp'||domain==='snow'||domain==='costs'?'kp.read':'pricing.read';const grants=access.grants.filter(g=>g.active&&g.permissions.includes(permission));const unrestricted=access.isAdmin||domain==='pricing'||grants.some(g=>g.scopeType==='network'&&g.scopeId==='dolomiti-nordicski');const base=[where('seasonId','==',seasonId),where('domain','==',domain)];const sets=unrestricted?[base]:grants.filter(g=>['organization','reportingArea'].includes(g.scopeType)).map(g=>[...base,where(g.scopeType==='organization'?'organizationId':'reportingAreaId','==',g.scopeId)]);const result=await Promise.all(sets.map(filters=>getDocs(query(collection(db,'historicalSeasonRecords'),...filters))));return result.flatMap(s=>s.docs.map(d=>({id:d.id,...d.data()} as RecordData)));}));
   const found=[...new Map(loaded.flat().map(r=>[r.id,r])).values()];let control:Summary|null=null;if(access.isAdmin){const snap=await getDoc(doc(db,'historicalSeasonImports',seasonId));if(snap.exists())control=snap.data() as Summary;}if(current){setRecords(found);setSummary(control);setStatus(found.length||control?'':it?'Storico non ancora disponibile per questo ambito.':'Historie für diesen Bereich noch nicht verfügbar.');}}
  load().catch(e=>{if(current)setStatus(e.message);});return()=>{current=false;};},[seasonId,domains.join(','),access,language,it]);
 const n=(v:unknown)=>typeof v==='number'?v.toLocaleString(it?'it-IT':'de-DE',{maximumFractionDigits:1}):v==null?'—':String(v);
 const product=(key:unknown)=>{const v=String(key);return PRODUCT_NAMES[v]?.[it?0:1]??v;};const areaLabel=(id:string)=>AREA_NAMES[id]?.[it?0:1]??id;
 const groups=[...new Map(records.filter(r=>r.reportingAreaId).map(r=>[r.reportingAreaId,records.filter(x=>x.reportingAreaId===r.reportingAreaId)])).values()];
 const totals=(rows:RecordData[])=>rows.flatMap(r=>r.facts).reduce<{q:number;e:number}>((a,f)=>({q:a.q+(typeof f.quantity==='number'?f.quantity:0),e:a.e+(typeof f.amount==='number'?f.amount:0)}),{q:0,e:0});
 const header=(it?'Area':'Region');
 if(seasonId==='2024-25'){
  const networkSales=records.find(r=>r.recordType==='annual-network-comparison');
  const annualTotals=networkSales?.facts.filter(f=>f.kind==='annualTotal')??[];
  const annualCategories=networkSales?.facts.filter(f=>f.kind==='annualCategory')??[];
  const networkCategories=networkSales?.facts.filter(f=>f.kind==='networkCategory')??[];
  const calculatedChange=networkSales?.facts.find(f=>f.kind==='calculatedChange');
  const sourceChange=calculatedChange?.sourceChangeRow as Record<string,unknown>|undefined;
  const networkSnow=records.find(r=>r.recordType==='seasonal-network-trail-summary');
  const southSnow=records.find(r=>r.recordType==='seasonal-subnetwork-trail-summary');
  const sourceNotes=records.find(r=>r.recordType==='source-notes');
  const printEuro=(v:unknown)=>typeof v==='number'?`€ ${n(v)}`:v==null?'—':String(v);
  const itemNames:Record<string,[string,string]>={
   'Technical snow production and delivery':['Produzione e distribuzione neve tecnica','Technische Schneeproduktion und -verteilung'],
   'Overall investment costs':['Investimenti complessivi','Gesamtinvestitionen'],
   'Investment plus technical snow production':['Investimenti + neve tecnica','Investitionen + technische Beschneiung'],
   'Implied investment component from combined total less snowmaking':['Componente investimenti ricostruita','Abgeleiteter Investitionsanteil'],
   'Cost per km of snowmaking track':['Costo per km di pista innevata','Kosten pro km beschneiter Loipe'],
   'Stored snow volume':['Volume neve conservata','Gespeichertes Schneevolumen'],
   'Snow depot total cost':['Costo totale deposito neve','Gesamtkosten Schneedepot'],
   'Electricity use':['Consumo elettrico','Stromverbrauch'],
  };
  const sourceDiverges=!!sourceChange&&typeof calculatedChange?.quantity==='number'&&typeof calculatedChange?.amount==='number'
   &&(sourceChange.quantity!==calculatedChange.quantity||sourceChange.amount!==calculatedChange.amount);
  const formatCostDetails=(f:Fact)=>[
   typeof f.snowmakingKm==='number'?`${n(f.snowmakingKm)} km`:null,
   typeof f.costPerKm==='number'?`${printEuro(f.costPerKm)}/${it?'km':'km'}`:null,
   typeof f.perOperatingDay==='number'?`${printEuro(f.perOperatingDay)}/${it?'giorno':'Tag'}`:null,
   typeof f.reportedOperatingDays==='number'?`${n(f.reportedOperatingDays)} ${it?'giorni':'Tage'}`:null,
   typeof f.minimum==='number'&&typeof f.maximum==='number'?`${printEuro(f.minimum)}–${printEuro(f.maximum)} ${String(f.amountBasis??'')}`:null,
   typeof f.snowVolumeMinM3==='number'&&typeof f.snowVolumeMaxM3==='number'?`${n(f.snowVolumeMinM3)}–${n(f.snowVolumeMaxM3)} m³`:null,
   typeof f.summerLossMinPct==='number'&&typeof f.summerLossMaxPct==='number'?`${n(f.summerLossMinPct)}–${n(f.summerLossMaxPct)}% ${it?'perdita estiva':'Sommerverlust'}`:null,
   typeof f.electricityKWh==='number'?`${n(f.electricityKWh)} kWh`:null,
   f.reportedAmountText?`${it?'dato originale':'Originalangabe'}: ${String(f.reportedAmountText)}`:null,
  ].filter(Boolean).join(' · ');
  return <div className="space-y-5">
   <section className="dns-card p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="dns-section-title">WS 2024–25 · {it?'Storico provvisorio':'Vorläufiger Historienstand'} · {it?'sola lettura':'schreibgeschützt'}</h2><p className="mt-2 max-w-3xl text-sm text-dns-muted">{it?'Primo punto della serie storica. Le vendite sono disponibili per area e categoria di biglietto; le fonti non contengono il dettaglio per partner. I due totali degli anni precedenti sono solo confronti di rete.':'Erster Punkt der historischen Reihe. Verkäufe liegen nach Region und Ticketkategorie vor; die Quellen enthalten keine Partnerdetails. Die beiden Vorjahre sind nur Netzwerkvergleiche.'}</p></div><span className="dns-pill">{it?'Dati provvisori':'Vorläufige Daten'}</span></div>{status&&<p role="status" className="mt-3 text-sm">{status}</p>}
    {module==='season'&&records.length>0&&<div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-lg border border-dns-mid/15 p-3"><div className="text-xs uppercase text-dns-muted">{it?'Fonti':'Quellen'}</div><div className="mt-1 font-semibold">{summary&&'sourceCount' in summary?String((summary as Record<string,unknown>).sourceCount):'3'}</div></div><div className="rounded-lg border border-dns-mid/15 p-3"><div className="text-xs uppercase text-dns-muted">{it?'Aree vendite':'Verkaufsregionen'}</div><div className="mt-1 font-semibold">{records.filter(r=>r.recordType==='reporting-area-product-totals').length}</div></div><div className="rounded-lg border border-dns-mid/15 p-3"><div className="text-xs uppercase text-dns-muted">{it?'Stato':'Status'}</div><div className="mt-1 font-semibold">{it?'Provvisorio · immutabile':'Vorläufig · unveränderlich'}</div></div></div>}
   </section>
   {(module==='season'||module==='sales'||module==='verification')&&networkSales&&<section className="dns-card p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="dns-section-title">{it?'Vendite DNS · confronto annuale':'DNS-Verkäufe · Jahresvergleich'}</h3><p className="mt-1 text-sm text-dns-muted">{it?'Totali dichiarati nel confronto annuale del workbook.':'Jahressummen aus dem Jahresvergleich des Arbeitsbuchs.'}</p></div>{calculatedChange&&<div className="rounded-lg bg-dns-bg px-4 py-3"><div className="text-xs uppercase text-dns-muted">2023–24 → 2024–25</div><div className="mt-1 font-semibold">+{n(calculatedChange.quantity)} {it?'biglietti':'Tickets'} · +{printEuro(calculatedChange.amount)}</div></div>}</div>
    <div className="mt-4 overflow-x-auto"><table className="dns-table"><thead><tr>{[it?'Stagione':'Saison',it?'Biglietti':'Tickets',it?'Vendite €':'Erlös €'].map(x=><th className="p-2 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{annualTotals.map(f=><tr key={String(f.seasonId)} className="border-t border-dns-mid/10"><td className="p-2 font-medium">{String(f.seasonId)}</td><td className="p-2 tabular-nums">{n(f.quantity)}</td><td className="p-2 tabular-nums">{printEuro(f.amount)}</td></tr>)}</tbody></table></div>
    {networkCategories.length>0&&<><h4 className="mt-5 text-sm font-semibold">{it?'Vendite 2024–25 per categoria':'Verkäufe 2024–25 nach Kategorie'}</h4><div className="mt-2 overflow-x-auto"><table className="dns-table"><thead><tr>{[it?'Categoria':'Kategorie',it?'Biglietti':'Tickets',it?'Vendite €':'Erlös €'].map(x=><th className="p-2 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{networkCategories.map(f=><tr key={String(f.productCode)} className="border-t border-dns-mid/10"><td className="p-2">{product(f.productCode)}</td><td className="p-2 tabular-nums">{n(f.quantity)}</td><td className="p-2 tabular-nums">{printEuro(f.amount)}</td></tr>)}</tbody></table></div></>}
    {sourceDiverges&&<p className="mt-3 rounded-md bg-amber-50 p-3 text-xs text-amber-950">{it?`La riga “sviluppo” del file riporta +${n(sourceChange?.quantity)} biglietti e ${printEuro(sourceChange?.amount)}. Il confronto qui sopra è calcolato dai totali annuali, che danno +${n(calculatedChange?.quantity)} e ${printEuro(calculatedChange?.amount)}. Entrambe le cifre sono conservate nella fonte.`:`Die Quelldatei nennt in der Zeile „Entwicklung“ +${n(sourceChange?.quantity)} Tickets und ${printEuro(sourceChange?.amount)}. Der Vergleich oben wird aus den Jahressummen berechnet: +${n(calculatedChange?.quantity)} und ${printEuro(calculatedChange?.amount)}. Beide Angaben bleiben dokumentiert.`}</p>}</section>}
   {(module==='season'||module==='kp')&&networkSnow&&<section className="dns-card p-6"><h3 className="dns-section-title">{it?'Piste e innevamento · rete DNS':'Loipen und Beschneiung · DNS-Netz'}</h3><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[it?'Km potenziali (testo)':'Potenzial (Text)',networkSnow.facts[0].reportedPotentialKm,'km'],[it?'Km potenziali (tabella)':'Potenzial (Tabelle)',networkSnow.facts[0].regionalTablePotentialKm,'km'],[it?'Km aperti':'Geöffnet',networkSnow.facts[0].regionalTableOpenKm,'km'],[it?'Apertura (testo / tabella)':'Öffnung (Text / Tabelle)',`${n(networkSnow.facts[0].reportedOpenSharePct)}% / ${n(networkSnow.facts[0].openSharePctFromRegionalTable)}%`,'']].map(([label,value,unit])=><div className="rounded-lg border border-dns-mid/15 p-3" key={String(label)}><div className="text-xs uppercase text-dns-muted">{String(label)}</div><div className="mt-1 text-lg font-semibold">{n(value)} {String(unit)}</div></div>)}</div><div className="mt-3 text-sm text-dns-muted">{it?`Innevamento riportato: ${n(networkSnow.facts[0].artificialSnowSharePct)}% artificiale e ${n(networkSnow.facts[0].naturalSnowSharePct)}% naturale. La tabella regionale somma ${n(networkSnow.facts[0].regionalTableSumPotentialKm)} km potenziali; il testo introduttivo ne riporta ${n(networkSnow.facts[0].reportedPotentialKm)}.`:`Laut Bericht: ${n(networkSnow.facts[0].artificialSnowSharePct)}% Kunstschnee und ${n(networkSnow.facts[0].naturalSnowSharePct)}% Naturschnee. Die regionale Tabelle summiert ${n(networkSnow.facts[0].regionalTableSumPotentialKm)} km Potenzial; der Einführungstext nennt ${n(networkSnow.facts[0].reportedPotentialKm)}.`}</div>
    {southSnow&&<div className="mt-4 rounded-lg bg-dns-bg p-4"><h4 className="text-sm font-semibold">{it?'Sottoinsieme Alto Adige':'Teilnetz Südtirol'}</h4><p className="mt-1 text-sm">{n(southSnow.facts[0].potentialKm)} km {it?'potenziali':'Potenzial'} · {n(southSnow.facts[0].openKm)} km {it?'aperti':'geöffnet'} · {n(southSnow.facts[0].reportedOpenSharePct)}% {it?'aperti':'geöffnet'} · {n(southSnow.facts[0].artificialSnowSharePct)}% {it?'neve artificiale':'Kunstschnee'}</p><p className="mt-1 text-xs text-dns-muted">{it?`La somma della tabella delle cinque aree è ${n(southSnow.facts[0].regionalTableSumPotentialKm)} km potenziali e ${n(southSnow.facts[0].regionalTableSumOpenKm)} km aperti.`:`Die regionale Tabelle der fünf Gebiete summiert ${n(southSnow.facts[0].regionalTableSumPotentialKm)} km Potenzial und ${n(southSnow.facts[0].regionalTableSumOpenKm)} km geöffnet.`}</p></div>}</section>}
   {groups.length>0&&groups.map(rows=>{const id=rows[0].reportingAreaId;const area=rows.find(r=>r.domain==='sales'||r.domain==='snow')?.label??areaLabel(id);const sales=rows.filter(r=>r.domain==='sales'&&r.recordType==='reporting-area-product-totals');const snow=rows.find(r=>r.domain==='snow'&&r.recordType==='seasonal-area-trail-summary');const costs=rows.filter(r=>r.domain==='costs');const total=totals(sales);return <details key={id} className="dns-card group p-0"><summary className="flex cursor-pointer list-none items-center gap-3 p-4 sm:p-5"><RegionLogos entityType="reportingArea" entityId={id}/><span className="min-w-0 flex-1"><span className="block font-semibold">{area}</span><span className="mt-1 block text-xs text-dns-muted">{sales.length>0?`${n(total.q)} ${it?'biglietti':'Tickets'} · € ${n(total.e)}`:''}{snow?` · ${n(snow.facts[0].openKm)} / ${n(snow.facts[0].potentialKm)} km ${it?'aperti':'geöffnet'}`:''}</span></span><span aria-hidden="true" className="text-dns-muted group-open:rotate-180">⌄</span></summary><div className="space-y-5 border-t border-dns-mid/15 p-4 sm:p-5">
      {sales.length>0&&<div><h4 className="text-sm font-semibold">{it?'Vendite per categoria':'Verkäufe nach Kategorie'}</h4><div className="mt-2 overflow-x-auto"><table className="dns-table"><thead><tr>{[it?'Biglietto':'Ticket',it?'Quantità':'Menge',it?'Incasso €':'Erlös €'].map(x=><th className="p-2 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{sales.flatMap(r=>r.facts).map((f,index)=><tr key={index} className="border-t border-dns-mid/10"><td className="p-2">{product(f.productCode)}</td><td className="p-2 tabular-nums">{n(f.quantity)}</td><td className="p-2 tabular-nums">{printEuro(f.amount)}</td></tr>)}</tbody><tfoot><tr className="border-t border-dns-mid/20 font-semibold"><td className="p-2">{it?'Totale area':'Gebiet gesamt'}</td><td className="p-2">{n(total.q)}</td><td className="p-2">{printEuro(total.e)}</td></tr></tfoot></table></div><p className="mt-2 text-xs text-dns-muted">{it?'Riepilogo area, senza righe partner o transazioni individuali.':'Regionalsumme, ohne Partner- oder Einzeltransaktionszeilen.'}</p></div>}
      {snow&&<div><h4 className="text-sm font-semibold">{it?'Piste e neve':'Loipen und Schnee'}</h4><div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{[[it?'Potenziali km':'Potenzial km',snow.facts[0].potentialKm],[it?'Aperti km':'Geöffnet km',snow.facts[0].openKm],[it?'Apertura %':'Öffnung %',snow.facts[0].openSharePct],[it?'Neve artificiale %':'Kunstschnee %',snow.facts[0].artificialSnowSharePct]].map(([label,value])=><div className="rounded-md bg-dns-bg p-3" key={String(label)}><div className="text-xs text-dns-muted">{String(label)}</div><div className="mt-1 font-semibold">{n(value)}{String(label).includes('%')?'%':''}</div></div>)}</div><p className="mt-2 text-xs text-dns-muted">{it?`Neve naturale: ${n(snow.facts[0].naturalSnowSharePct)}%. Fonte: report PDF, pagina ${n(snow.provenance?.sourcePage)}.`:`Naturschnee: ${n(snow.facts[0].naturalSnowSharePct)}%. Quelle: PDF-Bericht, Seite ${n(snow.provenance?.sourcePage)}.`}</p></div>}
      {costs.length>0&&<div><h4 className="text-sm font-semibold">{it?'Contesto dei costi · esempi del report':'Kostenkontext · Berichtsbeispiele'}</h4><div className="mt-2 overflow-x-auto"><table className="dns-table"><thead><tr>{[it?'Voce':'Posten',it?'Importo riportato':'Berichteter Betrag',it?'Altri indicatori':'Weitere Angaben'].map(x=><th className="p-2 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{costs.flatMap(r=>r.facts.map((f,i)=>{const amount=typeof f.reportedAmount==='number'?printEuro(f.reportedAmount):f.reportedAmountText?String(f.reportedAmountText):typeof f.minimum==='number'&&typeof f.maximum==='number'?`${printEuro(f.minimum)}–${printEuro(f.maximum)}`:'—';const title=itemNames[String(f.item)]?.[it?0:1]??String(f.item??'');const statusLabel=f.amountStatus==='inferred'?(it?' · valore ricostruito':' · abgeleitet'):'';return <tr key={`${r.id}-${i}`} className="border-t border-dns-mid/10 align-top"><td className="p-2">{title}{f.amountStatus==='inferred'&&<span className="ml-2 text-xs text-amber-800">{it?'stima':'Schätzung'}</span>}</td><td className="p-2 tabular-nums">{amount}{statusLabel}</td><td className="p-2 text-xs text-dns-muted">{formatCostDetails(f)}{f.note?` · ${String(f.note)}`:''}{r.provenance?.sourcePage?` · PDF p. ${String(r.provenance.sourcePage)}`:''}</td></tr>}))}</tbody></table></div><p className="mt-2 text-xs text-dns-muted">{it?'Esempi regionali e stime: non sono un totale dei costi della rete. I valori originali e le ricostruzioni sono distinti.':'Regionale Beispiele und Schätzungen, keine Gesamtkosten des Netzwerks. Originalwerte und abgeleitete Werte bleiben getrennt.'}</p></div>}
     </div></details>})}
   {annualCategories.length>0&&(module==='season'||module==='sales'||module==='verification')&&<details className="dns-card p-5"><summary className="cursor-pointer font-semibold">{it?'Apri il confronto delle categorie 2022–23 → 2024–25':'Kategorienvergleich 2022/23 → 2024/25 öffnen'}</summary><div className="mt-3 overflow-x-auto"><table className="dns-table"><thead><tr><th className="p-2 text-left">{it?'Categoria':'Kategorie'}</th>{['2022–23','2023–24','2024–25'].map(year=><th className="p-2 text-left" key={year}>{year}</th>)}</tr></thead><tbody>{annualCategories.map(category=>{const values=category.values as Array<Record<string,unknown>>;return <tr key={String(category.sourceProductLabel)} className="border-t border-dns-mid/10"><td className="p-2">{String(category.sourceProductLabel)}</td>{values.map(value=><td className="p-2" key={String(value.seasonId)}>{n(value.quantity)} · € {n(value.amount)}</td>)}</tr>})}</tbody></table></div><p className="mt-2 text-xs text-dns-muted">{it?'Per 2022–23 e 2023–24 l’Excel contiene solo i totali di rete. Lo storico completo di quelle stagioni potrà essere aggiunto con le relative fonti.':'Für 2022/23 und 2023/24 enthält die Excel-Datei nur Netzwerksummen. Vollständige Saisonstände können später mit den jeweiligen Quellen ergänzt werden.'}</p></details>}
   {sourceNotes&&<details className="dns-card p-5"><summary className="cursor-pointer font-semibold">{it?'Note e riconciliazioni della fonte':'Quellen- und Abstimmungsnotizen'}</summary><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-dns-muted">{sourceNotes.facts.map((f,i)=><li key={i}>{String(f.text)}</li>)}</ul></details>}
   {!records.length&&!status&&<section className="dns-card p-6">{it?'Nessun dato disponibile per questa scheda o per il tuo ambito.':'Keine Daten für diesen Bereich oder diese Berechtigung verfügbar.'}</section>}
  </div>;
 }
 return <div className="space-y-5">
  <section className="dns-card p-6"><h2 className="dns-section-title">WS {seasonId} · {it?'Storico':'Historie'} · {it?'sola lettura':'schreibgeschützt'}</h2><p className="mt-2 text-sm text-dns-muted">{it?'Dati per area e partner. Apri una regione per vedere il dettaglio.':'Daten nach Region und Partner. Region öffnen, um Details anzuzeigen.'}</p>{status&&<p role="status" className="mt-3 text-sm">{status}</p>}
   {module==='season'&&records.length>0&&<div className="mt-5 grid gap-3 sm:grid-cols-4">{['sales','orders','pricing','kp'].map(d=><div className="rounded-lg border border-dns-mid/15 p-3" key={d}><div className="text-xs uppercase text-dns-muted">{{sales:it?'Vendite': 'Verkäufe',orders:it?'Ordini':'Bestellungen',pricing:it?'Tariffe':'Preise',kp:'KP'}[d]}</div><div className="mt-1 font-semibold">{records.filter(r=>r.domain===d).length} {it?'partner':'Partner'}</div></div>)}</div>}
  </section>
  {module==='kp'&&<KPSeasonOverview seasonId={seasonId} language={language} records={records.filter((record)=>record.domain==='kp')} />}
  {summary&&summary.controls&&(module==='season'||module==='sales'||module==='verification')&&<section className="dns-card p-6"><h3 className="dns-section-title">{it?'Vendite dichiarate nel file':'Gemeldeter Verkauf laut Quelldatei'}</h3><div className="mt-3 flex flex-wrap gap-x-8 gap-y-2 text-lg"><span>{n(summary.reportedQuantity)} {it?'biglietti':'Tickets'}</span><span>€ {n(summary.reportedAmount)}</span></div><div className="mt-4 overflow-x-auto"><table className="dns-table"><thead><tr>{[header,it?'Quantità file':'Menge Datei',it?'Quantità dettagli':'Menge Details',it?'Importo file €':'Betrag Datei €',it?'Importo dettagli €':'Betrag Details €',it?'Scarto €':'Abweichung €'].map(x=><th className="p-2 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{summary.controls.map(c=><tr key={c.reportingAreaId}><td className="p-2">{areaLabel(c.reportingAreaId)}</td>{[c.reportedQuantity,c.detailQuantity,c.reportedAmount,c.detailAmount,c.amountDifference].map((v,i)=><td className={`p-2 ${i===4&&v?'font-semibold text-red-700':''}`} key={i}>{n(v)}</td>)}</tr>)}</tbody></table></div><p className="mt-3 text-xs text-dns-muted">{it?'Il riepilogo e i dettagli differiscono di 34 biglietti e 2.745 €. Entrambi i valori sono conservati.':'Gemeldete Summe und Details weichen um 34 Tickets und 2.745 € ab. Beide Werte bleiben erhalten.'}</p></section>}
  {module!=='kp'&&groups.map(rows=>{const id=rows[0].reportingAreaId;const sales=rows.filter(r=>r.domain==='sales');const total=totals(sales);const order=rows.filter(r=>r.domain==='orders');const kp=rows.filter(r=>r.domain==='kp');const pricing=rows.filter(r=>r.domain==='pricing');
   return <details key={id} className="dns-card group p-0"><summary className="flex cursor-pointer list-none items-center gap-3 p-4 sm:p-5"><RegionLogos entityType="reportingArea" entityId={id}/><span className="min-w-0 flex-1"><span className="block font-semibold">{areaLabel(id)}</span><span className="mt-1 block text-xs text-dns-muted">{sales.length} {it?'partner vendite':'Verkaufspartner'}{total.q?` · ${n(total.q)} ${it?'biglietti':'Tickets'} · € ${n(total.e)}`:''}</span></span><span aria-hidden="true" className="text-dns-muted group-open:rotate-180">⌄</span></summary>
    <div className="space-y-4 border-t border-dns-mid/15 p-4 sm:p-5">
     {sales.length>0&&<div><h4 className="text-sm font-semibold">{it?'Vendite per partner':'Verkäufe nach Partner'}</h4><div className="mt-2 overflow-x-auto"><table className="dns-table"><thead><tr>{[it?'Partner':'Partner',it?'Quantità':'Menge',it?'Valore €':'Wert €',''].map((x,i)=><th key={i} className="p-2 text-left">{x}</th>)}</tr></thead><tbody>{sales.map(r=>{const t=totals([r]);return <Fragment key={r.id}><tr className="border-t border-dns-mid/10"><td className="p-2"><span className="flex items-center gap-2"><RegionLogos entityType="organization" entityId={r.organizationId}/>{r.label}</span></td><td className="p-2">{n(t.q)}</td><td className="p-2">€ {n(t.e)}</td><td className="p-2"></td></tr><tr><td colSpan={4} className="p-0"><details><summary className="cursor-pointer px-2 pb-2 text-left text-[10px] font-semibold text-dns-mid underline underline-offset-2">{it?`Dettaglio · ${r.label}`:`Details · ${r.label}`}</summary><div className="max-w-full overflow-x-auto border-b border-dns-mid/10 bg-dns-bg px-3 py-2"><table className="dns-table max-w-[44rem]"><thead><tr><th className="p-2">{it?'Biglietto':'Ticket'}</th><th className="p-2">{it?'Canale':'Kanal'}</th><th className="p-2">{it?'Periodo':'Zeitraum'}</th><th className="p-2">{it?'Quantità':'Menge'}</th><th className="p-2">€</th></tr></thead><tbody>{r.facts.map((f,i)=><tr key={i} className="border-t border-dns-mid/10"><td className="p-2">{product(f.productCode)}</td><td className="p-2">{String(f.salesChannel)}</td><td className="p-2">{String(f.salesPeriod)}</td><td className="p-2 tabular-nums">{n(f.quantity)}</td><td className="p-2 tabular-nums">{n(f.amount)}</td></tr>)}</tbody></table></div></details></td></tr></Fragment>})}</tbody></table></div></div>}
     {order.length>0&&<div><h4 className="text-sm font-semibold">{it?'Ordini':'Bestellungen'}</h4><div className="mt-2 overflow-x-auto"><table className="dns-table"><thead><tr>{[it?'Partner':'Partner',it?'Categoria':'Kategorie',it?'Articoli':'Artikel'].map(x=><th className="p-2 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{order.map(r=><tr key={r.id} className="border-t border-dns-mid/10"><td className="p-2">{r.label}</td><td className="p-2">{r.id.includes('wristband')?(it?'Braccialetti':'Armbänder'):(it?'Tessere':'Tickets')}</td><td className="p-2">{r.facts.map(f=>`${String(f.item)}: ${n(f.quantity)}`).join(' · ')}</td></tr>)}</tbody></table></div></div>}
     {pricing.length>0&&<div><h4 className="text-sm font-semibold">{it?'Tariffe originali':'Quellpreise'}</h4><div className="mt-2 flex flex-wrap gap-2">{pricing.flatMap(r=>r.facts.map((f,i)=><span key={`${r.id}-${i}`} className="rounded bg-dns-bg px-3 py-2 text-sm">{String(f.item)} · {f.unitPrice==null?'—':`€ ${n(f.unitPrice)}`}</span>))}</div></div>}
     {kp.length>0&&<div><h4 className="text-sm font-semibold">{it?'Km neve per data di rilevazione':'Schneekilometer nach Stichtag'}</h4><div className="mt-2 overflow-x-auto"><table className="dns-table"><thead><tr>{[it?'Partner':'Partner',it?'Rilevazione':'Stichtag',it?'Riferimento km':'Referenz km',it?'Naturale km':'Naturschnee km',it?'Artificiale km':'Kunstschnee km'].map(x=><th className="p-2 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{kp.map(r=>r.facts.map((f,i)=><tr key={`${r.id}-${i}`} className="border-t border-dns-mid/10"><td className="p-2">{i===0?r.label:''}</td><td className="p-2">{String(f.date)}</td><td className="p-2">{n(f.referenceKm)}</td><td className="p-2">{n(f.naturalKm)}</td><td className="p-2">{n(f.artificialKm)}</td></tr>))}</tbody></table></div></div>}
    </div>
   </details>;
  })}
  {!records.length&&!status&&<section className="dns-card p-6">{it?'Nessun dato disponibile per questa selezione.':'Keine Daten für diese Auswahl verfügbar.'}</section>}
 </div>;
}
